version: 1.0.{build}

environment:
  matrix:
  - COMPILER: gcc
    PLATFORM: mingw64

install:
  # running under CI
  - set CI_TESTING=1
  - 'echo End intall at: & time /t'
  - SET PATH_ORIGINAL=%PATH%
  - SET "PATH_MINGW64=c:\msys64\mingw64\bin;c:\msys64\usr\bin"
  - SET PATH=%PATH_MINGW64%;%PATH_ORIGINAL%
  - SET WORKDIR=C:\projects
  - pacman -S --force mingw-w64-x86_64-cmake
  - pacman -S --force mingw-w64-x86_64-ninja
  - pacman -S --force mingw-w64-x86_64-clang       
  - pacman -S --force mingw-w64-x86_64-icu         
  - pacman -S --force mingw-w64-x86_64-libxml2     
  - pacman -S --force mingw-w64-x86_64-wineditline 
  - pacman -S --force mingw-w64-x86_64-winpthreads 
  - pacman -S --force mingw-w64-x86_64-pkg-config  
  - pacman -S --force mingw-w64-x86_64-dlfcn       
  - pacman -S --force make                         
  - pacman -S --force python                       
  - pacman -S --force python2                      

build_script:
  - cd
  - cd Src
  - gcc -o hello.exe hello.c

test_script:
  - 'echo test_script'
  - hello
