version: 1.0.{build}

environment:
  matrix:
  - COMPILER: gcc
    PLATFORM: mingw64

install:
  # Set Environment
  - 'echo End intall at: & time /t'
  - SET PATH_ORIGINAL=%PATH%
  - SET "PATH_MINGW64=c:\msys64\mingw64\bin;c:\msys64\usr\bin"
  - SET PATH=%PATH_MINGW64%;%PATH_ORIGINAL%
  - SET WORK_DIR=C:\projects
  - cd %WORK_DIR%
  
  # Install packages
  - pacman -S --noconfirm mingw-w64-x86_64-cmake
  - pacman -S --noconfirm mingw-w64-x86_64-ninja
  - pacman -S --noconfirm mingw-w64-x86_64-clang       
  - pacman -S --noconfirm mingw-w64-x86_64-icu         
  - pacman -S --noconfirm mingw-w64-x86_64-libxml2     
  - pacman -S --noconfirm mingw-w64-x86_64-wineditline 
  - pacman -S --noconfirm mingw-w64-x86_64-winpthreads 
  - pacman -S --noconfirm mingw-w64-x86_64-pkg-config  
  - pacman -S --noconfirm mingw-w64-x86_64-dlfcn       
  - pacman -S --noconfirm make                         
  - pacman -S --noconfirm python                       
  - pacman -S --noconfirm python2                      
  
  # Download source
  #- git clone https://github.com/apple/swift-cmark.git %WORK_DIR%/cmark
  #- cd %WORK_DIR%/cmark & git checkout -qf master & cd ..
  #- git clone https://github.com/tinysun212/swift-llvm-cygwin.git %WORK_DIR%/llvm
  #- cd %WORK_DIR%/llvm & git checkout -qf swift-4.0.3+mingw.20180102 & cd ..
  #- git clone https://github.com/tinysun212/swift-clang-cygwin.git %WORK_DIR%/clang
  #- cd %WORK_DIR%/clang & git checkout -qf swift-4.0.3+mingw.20180102 & cd ..
  - cd %WORK_DIR%
  - wget -q -O llvm_src.tar.gz https://github.com/tinysun212/swift-llvm-cygwin/archive/swift-4.0.3+mingw.20180102.tar.gz
  - tar zxf llvm_src.tar.gz
  - mv swift-llvm-cygwin-swift-4.0.3-mingw.20180102 llvm
  - wget -q -O clang_src.tar.gz https://github.com/tinysun212/swift-clang-cygwin/archive/swift-4.0.3+mingw.20180102.tar.gz
  - tar zxf clang_src.tar.gz
  - mv swift-clang-cygwin-swift-4.0.3-mingw.20180102 clang
  
  # instead of git clone swift
  #- c:/msys64/usr/bin/mkdir %WORK_DIR%/swift
  
build_script:
  # Build cmark
  #- c:/msys64/usr/bin/mkdir -p %WORK_DIR%/build/NinjaMinGW/cmark
  #- cd %WORK_DIR%/build/NinjaMinGW/cmark
  #- cmake -G Ninja -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ %WORK_DIR%/cmark
  #- ninja
  #- cd src
  #- cp -p libcmark.dll.a libcmark.a
  #- cp -p libcmark.a %WORK_DIR%/swift/libcmark.a
  
  # Build clang
  - cd %WORK_DIR%/llvm/tools
  - mklink /d clang ..\..\clang
  - c:/msys64/usr/bin/mkdir -p %WORK_DIR%/build/NinjaMinGW/llvm
  - cmake -G Ninja -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=clang  -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_ASSERTIONS:BOOL=TRUE %WORK_DIR%/llvm
  - ninja
  
test_script:
  - 'echo test_script'
  #- hello
